apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: vesterlid-io-tls
spec:
  secretName: vesterlid-io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: vesterlid.io
  dnsNames:
    - vesterlid.io
    - www.vesterlid.io
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - vesterlid.io
          - www.vesterlid.io
